# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];
  boot.kernelParams = ["psmouse.synaptics_intertouch=0"];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/8996aa27-6292-4b08-b5c7-3a82d3d5816e";
    fsType = "ext4";
  };
  fileSystems."/mnt/FastLane" = {
    device = "/dev/disk/by-label/Fast\x20Lane";
    fsType = "btrfs";
    options = [ "users" "nofail" "auto" "exec" ];
  };

  boot.initrd.luks.devices."luks-6ce9fb31-a07d-4f83-8606-ef70f7fa0b7a".device = "/dev/disk/by-uuid/6ce9fb31-a07d-4f83-8606-ef70f7fa0b7a";

  fileSystems."/boot/efi" = {
    device = "/dev/disk/by-uuid/34DE-77F6";
    fsType = "vfat";
  };

  swapDevices = [];

  # Bootloader.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  boot.loader.efi.efiSysMountPoint = "/boot/efi";

  # Setup keyfile
  boot.initrd.secrets = {
    "/crypto_keyfile.bin" = null;
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp4s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  # powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
